### ISSUE TITLE
build info

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#16]
Each build increments a counter.
this is triggered by buildinfo.sh. And in info.plist the counter is written. This means that each comitt also unnecessarily changes info.plist.

Alone this was not a big problem.

But now in the team there must be another solution for a build-info.

**Comment by MyMattes** [comment]
I'd suggest to use the build directory instead of the info.plist at its source location: This way the build product will have the correct build number, but the git-controlled source code remains unchanged. Could be achieved by using this path assignment:
`plist="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"`

**Comment by MyMattes** [comment]
I changed _buildinfo.sh_ to work with git information exclusively to determine app version and build number: As a change not every single build is counted (but commits) and an new app version is reflected by a git tag. The Settings bundle is automatically updated. Here's the pull request: #36
